version: '2'

services:
  stock_db:
    restart: always
    image: postgres

    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d
      
    expose:
      - "5432"
    ports:
      - "54321:5432"

  server:
    build: ./matching-server
    command: ./server
    volumes:
      - ./matching-server:/code
    expose:
      - "12345"
    ports:
      - "12345:12345"
    depends_on:
      - stock_db
